# ----------- CONFIGURABLE START -----------
title:            "mainnet.lightwalletd.com:9067 // testnet.lightwalletd.com:9067"
description:      "Zcash public mainnet & testnet lightwalletd service funded by ZOMG"
url:              http://lightwalletd.com # Site url, without a slash at the end.
signoff:          "lightwalletd" # Your name
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Home
    url:          /
    external:     false
  - name:         Docs
    url:          /docs
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"