# ----------- CONFIGURABLE START -----------
title:            "mainnet.lightwalletd.com:9067 // testnet.lightwalletd.com:9067"
description:      "Zcash public mainnet & testnet lightwalletd service funded by ZOMG"
url:              https://lightwalletd.com # Site url, without a slash at the end.
signoff:          "lightwalletd" # Your name
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Warrant Canary
    url:          /
    external:     false
  - name:         Disclosure Policy
    url:          /disclosure
    external:     false
  - name:         Links
    url:          /links
    external:     false
  - name:         Status
    url:          https://status.lightwalletd.com
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"